# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\x12\x05\x63loud\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"U\n\rSignupRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x04 \x01(\t\"?\n\rEnrollRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"0\n\x0fOtpVerification\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\";\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t2\xd4\x01\n\x0bUserService\x12-\n\x05login\x12\x13.cloud.LoginRequest\x1a\x0f.cloud.Response\x12/\n\x06signup\x12\x14.cloud.SignupRequest\x1a\x0f.cloud.Response\x12/\n\x06\x65nroll\x12\x14.cloud.EnrollRequest\x1a\x0f.cloud.Response\x12\x34\n\tverifyOtp\x12\x16.cloud.OtpVerification\x1a\x0f.cloud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=30
  _globals['_LOGINREQUEST']._serialized_end=80
  _globals['_SIGNUPREQUEST']._serialized_start=82
  _globals['_SIGNUPREQUEST']._serialized_end=167
  _globals['_ENROLLREQUEST']._serialized_start=169
  _globals['_ENROLLREQUEST']._serialized_end=232
  _globals['_OTPVERIFICATION']._serialized_start=234
  _globals['_OTPVERIFICATION']._serialized_end=282
  _globals['_RESPONSE']._serialized_start=284
  _globals['_RESPONSE']._serialized_end=343
  _globals['_USERSERVICE']._serialized_start=346
  _globals['_USERSERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
